### ISSUE TITLE
Figure out a way to force LLCs to fully present peptides through H2Kb/H2Db

### ISSUE THREAD

**Issue by armish** [hammerlab/tcr-transfer#3]
From me to Mark (9/27):

> Here is my first try at forcing LLCs to present more of the pulsed-peptide. It does look like LLCs lack proper H2Kb expression and doesn't present the peptide unless treated with IFNg. This is a opposed to MC38Bs, where they readily present SIINFEKL and have high H2k expression. Need to get that LLC presentation level even higher to be able to carry out a proper killing screen with them. Will do more optimization on this one.

![Presentation - LLC (1)](https://user-images.githubusercontent.com/7809/67117778-84247d00-f1b1-11e9-8cc5-c3a3365f44a5.png)
![Presentation - MC38B (1)](https://user-images.githubusercontent.com/7809/67117779-84247d00-f1b1-11e9-8faf-6663d2219fd3.png)

From me to Mark (10/2):

> Hmm, increasing the IFNg dosage didn't help with the presentation (still half of them are presenting and half are not). Going to test if that presenting/non-presenting distinction can be explained by the suspension/adherent natures of these cells on Friday as you recommended.

![Presentation (1)](https://user-images.githubusercontent.com/7809/67117921-c5b52800-f1b1-11e9-9b40-0ede55791528.png)

Tried to collect the supernatant to enrich for floating cells to see if they were the ones who are not presenting but it is really hard to collect loosely-attached cells just with the supernatant. And if I pipette up/down hard, then all the cells come out of the plate.

The next goal is to image them in plate and see which cells are responsible for not presenting.

**Comment by armish** [comment]
@elinorgottschalk ICYMI this thread. You get some expression/presentation out of LLCs with O/N IFNg treatment but increasing the dosage doesn't really help.

**Comment by armish** [comment]
@elinorgottschalk ICYMI this thread. You get some expression/presentation out of LLCs with O/N IFNg treatment but increasing the dosage doesn't really help.

**Comment by elinorgottschalk** [comment]
LLCs are able to present SIINFEKL or gp100 and activate OT-I or pmel expressing T cells, respectively. But none of the LLC NeoTCRs were able to activate T cells cocultured with the LLCs. May screen the LLC NeoTCRs with the neoantigen peptides that Mark/John have. I will try out that larger screen with the MC38B peptides first though, once they arrive.   

![20210331 Project Overview (3)](https://user-images.githubusercontent.com/43008944/121546292-2de4fd00-c9d9-11eb-83b6-5451f8df8236.png)
![20210517 (1)](https://user-images.githubusercontent.com/43008944/121546293-2e7d9380-c9d9-11eb-9a8b-09690cd8be8e.png)
![20210517](https://user-images.githubusercontent.com/43008944/121546295-2e7d9380-c9d9-11eb-8b1f-faf7f23841ae.png)
