### ISSUE TITLE
Knock H2Kb and H2Db out from MC38Bs

### ISSUE THREAD

**Issue by armish** [hammerlab/tcr-transfer#6]
Either of them should save these cells from the cytotoxicity coming from the TCRs we have discovered. If we can work this out, it will make it easier to come up with a candidate list once we are done with (#5). We can order specific sgRNAs from Synthego for these.

**Comment by armish** [comment]
Just ordered 6 sgRNAs for each target: H2-K1 and H2-D1

Designed gRNAs using Broad's GPP portal: [20191105 - H2Kb_H2Db gRNA designs.xlsx](https://github.com/hammerlab/tcr-transfer/files/3811069/20191105.-.H2Kb_H2Db.gRNA.designs.xlsx)
and ordered through Synthego: [Synthego - Tube Upload Template ### 2.xlsx](https://github.com/hammerlab/tcr-transfer/files/3811070/Synthego.-.Tube.Upload.Template.2.xlsx)

**Comment by elinorgottschalk** [comment]
We were successful at knocking out both Kb and Db.

![20210331 Project Overview](https://user-images.githubusercontent.com/43008944/121544859-0477a180-c9d8-11eb-97ed-5e7c97baf54f.png) 
![20210331 Project Overview (1)](https://user-images.githubusercontent.com/43008944/121544851-03467480-c9d8-11eb-9f82-583167d9651d.png)
