### ISSUE TITLE
Try to see if our MC38B TCRs can recognize previously described epitope candidates

### ISSUE THREAD

**Issue by armish** [hammerlab/tcr-transfer#7]
For example, from this paper: [Predicting immunogenic tumour mutations by combining mass spectrometry and exome sequencing](https://www.ncbi.nlm.nih.gov/pubmed/25428506):

Gene | Peptide | MHC allele | IC50 (mut) | IC50 (WT) | Mutation position | Immunogenicity prediction
-- | -- | -- | -- | -- | -- | --
Dpagt1 | SIIVFNL[V/L] | H-2Kb | 8 | 34 | Anchor (P8) | −
Reps1 | AQL[P/A]NDVVL | H-2Db | 9 | 100 | Solvent (P4) | +
Adpgk | ASMTN[R/M]ELM | H-2Db | 2 | 3 | Solvent (P6) | +
Cpne1 | SSP[D/Y]SLHYL | H-2Db | 211 | 685 | Solvent (P4) | −
Irgq | AALLNSA[G/V]L | H-2Db | 3 | 52 | Solvent (P8) | −
Aatf | MAPIDHT[A/T]M | H-2Db | 30 | 102 | Solvent (P8) | −
Med12 | DPSSSVLFE[D/Y] | H-2Kb | 38,300 | 39,411 | No structure | −

and looks like these pentamers are sold by Proimmune: https://www.proimmune.com/list-of-catalog-pentamers/

We can also try to get these peptides synthesized and pulse a non-MC38 cell line with them to see if they make it susceptible to our TCRs.

**Comment by elinorgottschalk** [comment]
[Quote from VWR for the two pentamers ](https://drive.google.com/drive/folders/0Bxm6tv6xH4vzeWZnN2wwOFpWR0k)that have worked for Aaron Ring's group (Reps1 and Adpgk).

**Comment by elinorgottschalk** [comment]
I noticed the pentamer order has been put on hold by VWR. I enquired and received this email from John Herczogh (VWR rep): 

> Since this ships from UK. VWR is asking for “the importer of record”, which is defined as:
“Importer of record refers to an importer, whether an entity or individual, who is responsible for ensuring that legal goods are imported in accordance with the law of the place. Importer is responsible for filing legally required documents.”
So I have been trying to get definition of this and release your order to the vendor. It is in “hold” right now until we get this info from you / or handled. 
I am now asking for a form or what do I send to you so you can meet the requirements of “importer or record”.  Or, how can I assist in getting this requirement taken care of. FYI. 
Sorry for the delay.

**Comment by elinorgottschalk** [comment]
Update from John to me:

> Just got word, that you order has been released to the vendor.  Yay !!  not sure on leadtime, but they have it now.

**Comment by armish** [comment]
I just requested a quote from GenScript for the 7 peptides the Genscript paper identified:

[MC38B-Custom_Peptide Batch_Order_Form.xlsx](https://github.com/hammerlab/tcr-transfer/files/4036539/MC38B-Custom_Peptide.Batch_Order_Form.xlsx)

Given that with the T cell activation assay, Jurkat-NFATs are strongly reactive against pulsed cells, we will try to pulse MC38s with these one by one against each TCR candidate and see if we can get a good signal out of it (this is rather than trying to stain with the dextramer, which is not that reliable and is an expensive method with no proper negative/positive control.

**Comment by elinorgottschalk** [comment]
Just realized that only 6 of the 7 peptides arrived 1/23/2020 - we didn't receive the first one on the list above (Dpagt1) and it wasn't included in the solubility/QC reports. I see that it was included on the peptide batch order form. @armish did GenScript say anything to you about Dpagt1?

**Comment by armish** [comment]
@elinorgottschalk looks like the last peptide is still "in production". I will reach out and see what their ETA is ⏳

**Comment by armish** [comment]
From them:

![Screenshot_20200201-121826~2](https://user-images.githubusercontent.com/7809/73596100-337d2980-44ed-11ea-973e-0aedba83d68f.png)

From me (2/1):

> Hi all,

> Thank you so much for getting most of the peptides ready so quickly. I saw that the first item is still in the works and I was wondering if you have a rough ETA for that last bit.

> I am CC'ing Elinor from our lab who is leading this project
> 
> Thanks!

**Comment by elinorgottschalk** [comment]
Mark pointed me to this paper: [Identification of a neo-epitope dominating endogenous CD8 T cell responses to MC-38 colorectal cancer](https://www.tandfonline.com/doi/full/10.1080/2162402X.2019.1673125). 
It might be a good idea to get peptides synthesized from these four other predicted neoantigens :

- Gtf2i (STYVIPRL) Kb 
- Rpl18 (KILTFDRL) Kb 
- Tdg (RALDKVHYYI) Db 
- Wbp11 (DAVKNAQHL) Db

Especially since two of them are presented by Kb and it looks like three of the candidate TCRs are Kb-dependent. Are these mutations present in our sequencing data @armish?

**Comment by elinorgottschalk** [comment]
Sent a new peptide request to Genscript for the above peptides. 
[MC38B-2-Custom_Peptide.Batch_Order_Form.xlsx](https://github.com/hammerlab/tcr-transfer/files/4182905/MC38B-2-Custom_Peptide.Batch_Order_Form.xlsx)

**Comment by armish** [comment]
> @elinorgottschalk: Especially since two of them are presented by Kb and it looks like three of the candidate TCRs are Kb-dependent. Are these mutations present in our sequencing data?

Looks like we have two of them: `Gtf2i` and `Wbp11`; but I would still go ahead and order all of them to be comprehensive as there is a chance that the mutations are not there but they can still create an immune response (like the way human gp100 creates against the mouse one).

**Comment by elinorgottschalk** [comment]
All of the previously described neoepitopes have been tested with our MC38B NeoTCRs. Two peptides appear to be able to activate T cells expressing TCR30, however only one results in activation levels comparable to the SIINFEKL/OT-I condition.

<img width="353" alt="MC38B-TCRs-all-peptides" src="https://user-images.githubusercontent.com/43008944/121548891-61c12200-c9db-11eb-9015-bca43ccc284e.png">

![20210505-titrations](https://user-images.githubusercontent.com/43008944/121549052-83220e00-c9db-11eb-82e6-a78f7d9e56a2.png)
